export const ROUTES = {
  NOT_MATCH: '/404',
  LOGIN: '/login',
  REGISTER: '/register',
  DASHBOARD: '/app/dashboard',
  CREATE_PRODUCT: '/app/product/create',
  PRODUCT_LIST: '/app/product',
  PRODUCT_DETAILS: '/app/product/:id',
  CREATE_ORDER: '/app/order/create',
  ORDER_LIST: '/app/order',
  ORDER_DETAILS: '/app/order/:id',
  CREATE_RECEIPT: '/app/receipt/create',
  RECEIPT_LIST: '/app/receipt',
  RECEIPT_DETAILS: '/app/receipt/:id',
};
