export const ROUTES = {
  NOT_MATCH: '/app/404',
  AUTH_GOOGLE: '/auth/google',
  LOGIN: '/login',
  REGISTER: '/register',
  DASHBOARD: '/app/dashboard',
  CREATE_PRODUCT: '/app/product/create',
  PRODUCT_LIST: '/app/product',
  PRODUCT_DETAILS: '/app/product/:id',
  CREATE_ORDER: '/app/order/create',
  ORDER_LIST: '/app/order',
  ORDER_DETAILS: '/app/order/:id',
  CREATE_RECEIPT: '/app/receipt/create',
  RECEIPT_LIST: '/app/receipt',
  RECEIPT_DETAILS: '/app/receipt/:id',
  COURIER_TRACKING: '/app/receipt/track/:id',
  SETTINGS: '/app/settings',
  TEAM: '/app/team',
  CREATE_USER: '/app/team/create',
  CHAT: '/app/chat',
  KNOWLEDGE: '/app/knowledge',
};
